
version: 2

sources:
  - name: public
    tables:
      - name: discord_data
      - name: events_log

models:
  - name: discord_members
    description: contagem de membros
    columns:
      - name: extracted_at
        description: Data da contagem
        tests:
          - unique
      - name: approximate_member_count
        description: quantidade aproximada de membros
        tests:
          - not_null
      - name: approximate_presence_count
        description: quantidade aproximada de membros online
        tests:
          - not_null


  - name: events
    description: Eventos relevantes para algum impacto nas analises
    columns:
      - name: event_name
        description: Nome do evento
        tests:
          - unique
      - name: occurred_at
        description: Data do acontecimento do evento
        tests:
          - not_null
      - name: kind
        description: Tipo de evento
        tests:
          - not_null
